import React, { useEffect, useMemo, useRef, useState } from "react";
import { LineChart, Line, ResponsiveContainer, Tooltip, YAxis } from "recharts";
import { Activity, BarChart3, Crown, Copy, LogIn, LogOut, Pause, Play, Plus, RotateCcw, Send, Trophy, Users, Zap } from "lucide-react";
import { getClientId, read, write } from "./storage";

const COMPANIES = [
  ["ARSR","Alpine ReSecure","Insurance",1800,.008], ["BRSK","Bavaria Risk ReSecure","Insurance",1600,.013],
  ["UNSA","UnityShield Assurance","Insurance",950,.011], ["SGIN","SummitGuard Insurance","Insurance",700,.007],
  ["FTSG","FortiSure Insurance Group","Insurance",550,.011], ["CCBK","Capital Crest","Banking",1250,.005],
  ["GLDC","Goldcrest Capital","Banking",2400,.009], ["SPFN","Sterling Peak Financial","Banking",1900,.014],
  ["GHBK","Global Horizon Bank","Banking",850,.008], ["VTCS","Vertex Consulting Solutions","Consulting",1450,.014],
  ["SNXA","Strategic Nexus Advisors","Consulting",1100,.017], ["PRAD","Pinnacle Risk Advisors","Consulting",900,.008],
].map(([ticker,name,sector,base,vol])=>({ticker,name,sector,base,vol}));
const SECTORS=["Insurance","Banking","Consulting"];
const START_CASH=100000, TICK=3000, POLL=1200, HISTORY=45;
const colors={Insurance:"#4fd1c5",Banking:"#e8b34c",Consulting:"#b18cff"};
const money=n=>Math.round(n).toLocaleString("en-IN");
const money2=n=>Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
const id=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const fresh=()=>({tick:0,paused:false,speed:1,prices:Object.fromEntries(COMPANIES.map(c=>[c.ticker,c.base])),history:Object.fromEntries(COMPANIES.map(c=>[c.ticker,Array.from({length:HISTORY},(_,i)=>({t:i,p:c.base}))])),news:[{id:id(),text:"Market opened. Waiting for the first move.",tone:"neutral"}],event:null,updatedAt:Date.now()});
function nextMarket(s){
  const prices={...s.prices}, history={...s.history};
  COMPANIES.forEach(c=>{const p=prices[c.ticker]; const move=p*c.vol*(Math.random()*2-1)+((c.base-p)*.006); const n=Math.max(c.base*.75,Math.min(c.base*1.25,p+move)); prices[c.ticker]=Math.round(n*100)/100; history[c.ticker]=[...history[c.ticker].slice(-HISTORY+1),{t:s.tick+HISTORY,p:prices[c.ticker]}];});
  let news=s.news;
  if(Math.random()<.06){const c=COMPANIES[Math.floor(Math.random()*COMPANIES.length)]; const up=prices[c.ticker]>=c.base; news=[{id:id(),text:`${c.ticker} ${up?"rallies":"falls"} as market sentiment shifts.`,tone:up?"up":"down"},...news].slice(0,12);}
  return {...s,prices,history,news,tick:s.tick+1,updatedAt:Date.now()};
}
function App(){
  const client=getClientId();
  const [screen,setScreen]=useState("home"),[room,setRoom]=useState(""),[playerName,setPlayerName]=useState(""),[isHost,setIsHost]=useState(false),[hostKey,setHostKey]=useState(""),[market,setMarket]=useState(fresh),[portfolio,setPortfolio]=useState({cash:START_CASH,holdings:{},name:""}),[players,setPlayers]=useState([]),[selected,setSelected]=useState("ARSR"),[qty,setQty]=useState(1),[filter,setFilter]=useState("All"),[tab,setTab]=useState("market"),[notice,setNotice]=useState(""),[eventScope,setEventScope]=useState("market"),[eventTarget,setEventTarget]=useState("Insurance"),[eventPct,setEventPct]=useState(10),[headline,setHeadline]=useState("");
  const roomScope=room?`room:${room}`:"";
  const playerScope=room&&client?`room:${room}:player:${client}`:"";
  const timer=useRef(null);
  const selectedCompany=COMPANIES.find(c=>c.ticker===selected)||COMPANIES[0];
  const visible=useMemo(()=>filter==="All"?COMPANIES:COMPANIES.filter(c=>c.sector===filter),[filter]);
  const netWorth=portfolio.cash+Object.entries(portfolio.holdings||{}).reduce((a,[t,q])=>a+(market.prices[t]||0)*q,0);

  const savePlayer=async(p=portfolio)=>{if(playerScope) await write(playerScope,"portfolio",{...p,name:playerName||p.name});};
  const joinRoom=async(code,name,host=false,key="")=>{
    const r=code.trim().toUpperCase(); if(!r||!name.trim()) return setNotice("Enter a room code and your name.");
    const state=await read(`room:${r}`,"state"); if(!state) return setNotice("Room not found. Ask the host for the correct code.");
    setRoom(r);setPlayerName(name.trim());setIsHost(host);setHostKey(key);setMarket(state);
    const ps={cash:START_CASH,holdings:{},name:name.trim(),clientId:client,joinedAt:Date.now(),host};
    const existing=await read(`room:${r}:player:${client}`,"portfolio"); setPortfolio(existing||ps); if(!existing) await write(`room:${r}:player:${client}`,"portfolio",ps);
    setScreen("game");setNotice(`Joined ${r}`);
  };
  const createRoom=async()=>{const code=id();const key=id()+id();const state=fresh();state.hostClient=client;state.hostKey=key;await write(`room:${code}`,"state",state);await write(`room:${code}:player:${client}`,"portfolio",{cash:START_CASH,holdings:{},name:playerName.trim()||"Headmaster",clientId:client,joinedAt:Date.now(),host:true});setRoom(code);setHostKey(key);setIsHost(true);setPlayerName(playerName.trim()||"Headmaster");setMarket(state);setPortfolio({cash:START_CASH,holdings:{},name:playerName.trim()||"Headmaster"});setScreen("game");setNotice(`Room ${code} created.`);};
  useEffect(()=>{if(!roomScope)return; let live=true; const load=async()=>{try{const s=await read(roomScope,"state");if(s&&live)setMarket(s);const p=await read(playerScope,"portfolio");if(p&&live)setPortfolio(p);}catch(e){if(live)setNotice("Connection error. Check Supabase settings.");}};load();const poll=setInterval(load,POLL);return()=>{live=false;clearInterval(poll)}},[roomScope,playerScope]);
  useEffect(()=>{if(!isHost||!roomScope)return;clearInterval(timer.current);if(market.paused)return;timer.current=setInterval(async()=>{const latest=await read(roomScope,"state");if(!latest||latest.paused)return;const s=nextMarket(latest);await write(roomScope,"state",s);setMarket(s)},TICK/Math.max(.5,market.speed));return()=>clearInterval(timer.current)},[isHost,roomScope,market.paused,market.speed]);
  useEffect(()=>{if(!isHost||!roomScope)return;let live=true;const load=async()=>{const rows=await Promise.all([...Array(40)].map(async(_,i)=>null));void rows;const out=[];for(let i=0;i<30;i++){const p=await read(`${roomScope}:player:${i}`,"portfolio");if(p)out.push(p)}if(live&&out.length)setPlayers(out)}; // players are also discovered through an index below
    const poll=async()=>{const idx=await read(roomScope,"players");if(idx?.length){const out=[];for(const pid of idx){const p=await read(`${roomScope}:player:${pid}`,"portfolio");if(p)out.push(p)}if(live)setPlayers(out)}};poll();const x=setInterval(poll,1800);return()=>{live=false;clearInterval(x)}},[isHost,roomScope]);
  useEffect(()=>{if(roomScope&&playerScope&&screen==="game"){read(roomScope,"players").then(list=>{const a=Array.isArray(list)?list:[];if(!a.includes(client))write(roomScope,"players",[...a,client])})}},[roomScope,playerScope,screen]);
  const trade=async(side)=>{const p=selectedCompany, q=Math.max(1,Math.floor(Number(qty)||1)),price=market.prices[p.ticker];if(side==="buy"){const cost=price*q;if(cost>portfolio.cash)return setNotice("Not enough cash.");const n={...portfolio,cash:portfolio.cash-cost,holdings:{...portfolio.holdings,[p.ticker]:(portfolio.holdings[p.ticker]||0)+q}};setPortfolio(n);await savePlayer(n);setNotice(`Bought ${q} ${p.ticker}`)}else{const have=portfolio.holdings[p.ticker]||0;if(q>have)return setNotice("You do not own enough shares.");const h={...portfolio.holdings,[p.ticker]:have-q};if(!h[p.ticker])delete h[p.ticker];const n={...portfolio,cash:portfolio.cash+price*q,holdings:h};setPortfolio(n);await savePlayer(n);setNotice(`Sold ${q} ${p.ticker}`)}};
  const togglePause=async()=>{const s={...market,paused:!market.paused,updatedAt:Date.now()};setMarket(s);await write(roomScope,"state",s)};
  const reset=async()=>{const s=fresh();s.hostClient=client;s.hostKey=hostKey;await write(roomScope,"state",s);setMarket(s);setNotice("Market reset.")};
  const fireEvent=async()=>{const s={...market,prices:{...market.prices},history:{...market.history},news:[...market.news],event:null};COMPANIES.forEach(c=>{const hit=eventScope==="market"||eventScope==="sector"&&c.sector===eventTarget||eventScope==="company"&&c.ticker===eventTarget;if(hit){const n=Math.max(c.base*.75,Math.min(c.base*1.25,s.prices[c.ticker]*(1+Number(eventPct)/100)));s.prices[c.ticker]=Math.round(n*100)/100;s.history[c.ticker]=[...s.history[c.ticker].slice(-HISTORY+1),{t:s.tick+HISTORY,p:s.prices[c.ticker]}]}});const label=eventScope==="market"?"MARKET":eventScope==="sector"?eventTarget:eventTarget; s.news=[{id:id(),text:`${label}: ${headline||`Headmaster event ${Number(eventPct)>=0?"+":""}${eventPct}%`}`,tone:Number(eventPct)>=0?"up":"down"},...s.news].slice(0,12);await write(roomScope,"state",s);setMarket(s);setNotice("Event published to every player.")};
  const copyRoom=()=>navigator.clipboard?.writeText(room).then(()=>setNotice("Room code copied."));
  const leave=()=>{setScreen("home");setRoom("");setIsHost(false);setHostKey("");setNotice("")};

  if(screen==="home")return <div className="app"><header><div><div className="brand">STOCK<span>EX</span> <small>TRADING FLOOR</small></div><div className="sub">LIVE MULTIPLAYER MARKET SIMULATION</div></div><div className="live"><i/> ONLINE</div></header><main className="hero"><section className="heroCard"><div className="eyebrow"><Zap size={14}/> CLASSROOM / COMPETITION MODE</div><h1>Run your own<br/><span>stock market.</span></h1><p>Create a live room, invite players with one code, and control the market from the Headmaster panel.</p><div className="homeGrid"><div className="joinBox"><h3><Crown size={18}/> HOST A GAME</h3><input value={playerName} onChange={e=>setPlayerName(e.target.value)} placeholder="Your name"/><button onClick={createRoom}><Plus size={16}/> CREATE LIVE ROOM</button><div className="hint">You become the Headmaster. Prices move every 3 seconds.</div></div><div className="joinBox"><h3><LogIn size={18}/> JOIN A GAME</h3><input value={room} onChange={e=>setRoom(e.target.value.toUpperCase())} placeholder="6-character room code" maxLength={12}/><input value={playerName} onChange={e=>setPlayerName(e.target.value)} placeholder="Your name"/><button className="secondary" onClick={()=>joinRoom(room,playerName)}><LogIn size={16}/> JOIN ROOM</button></div></div></section><section className="featureRow"><div><Users/> <b>Multiplayer</b><span>Everyone sees the same market.</span></div><div><BarChart3/> <b>Live charts</b><span>Every company has its own graph.</span></div><div><Zap/> <b>Headmaster events</b><span>Move the market on command.</span></div></section></main><footer>STOCKEX • Educational simulation • Not real-money trading</footer></div>;

  const leaderboard=players.map(p=>({...p,worth:(p.cash||0)+Object.entries(p.holdings||{}).reduce((a,[t,q])=>a+(market.prices[t]||0)*q,0)})).sort((a,b)=>b.worth-a.worth);
  return <div className="app"><header><div><div className="brand">STOCK<span>EX</span> <small>TRADING FLOOR</small></div><div className="sub">ROOM <b>{room}</b> • {isHost?"HEADMASTER":"PLAYER"}</div></div><div className="headActions"><button className="roomBtn" onClick={copyRoom}><Copy size={14}/> {room}</button><button className="ghost" onClick={leave}><LogOut size={14}/> LEAVE</button></div></header>
    <nav className="tabs"><button className={tab==="market"?"active":""} onClick={()=>setTab("market")}>MARKET</button><button className={tab==="portfolio"?"active":""} onClick={()=>setTab("portfolio")}>MY PORTFOLIO</button>{isHost&&<button className={tab==="control"?"active":""} onClick={()=>setTab("control")}>HEADMASTER</button>}<div className="marketStatus"><i className={market.paused?"off":""}/>{market.paused?"PAUSED":"LIVE"} • TICK {market.tick}</div></nav>
    {notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    <main className="workspace">{tab==="market"&&<><section className="marketGrid"><div className="companies"><div className="sectionTitle"><div><span>COMPANY BOARD</span><h2>Market</h2></div><div className="filters"><button className={filter==="All"?"sel":""} onClick={()=>setFilter("All")}>ALL</button>{SECTORS.map(s=><button className={filter===s?"sel":""} onClick={()=>setFilter(s)} key={s}>{s}</button>)}</div></div>{visible.map(c=>{const price=market.prices[c.ticker],change=((price-c.base)/c.base)*100,up=change>=0;return <div className="company" key={c.ticker} onClick={()=>setSelected(c.ticker)}><div className="companyName"><b>{c.ticker}</b><span>{c.name}</span><em style={{color:colors[c.sector]}}>{c.sector}</em></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={market.history[c.ticker]}><YAxis domain={["dataMin","dataMax"]} hide/><Tooltip contentStyle={{background:"#10151d",border:"1px solid #2c3440",fontSize:10}} formatter={v=>[money2(v),"Price"]}/><Line dataKey="p" type="monotone" stroke={up?"#33d17a":"#ff5c73"} dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div><div className="quote"><b>₹{money2(price)}</b><span className={up?"up":"down"}>{up?"▲":"▼"} {Math.abs(change).toFixed(2)}%</span></div></div>})}</div><aside className="ticket"><div className="panelTitle"><span>ORDER TICKET</span><Activity size={16}/></div><div className="selected"><b>{selectedCompany.ticker}</b><span>{selectedCompany.name}</span><strong>₹{money2(market.prices[selectedCompany.ticker])}</strong></div><label>QUANTITY</label><input type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><div className="orderValue">ORDER VALUE <b>₹{money2(market.prices[selectedCompany.ticker]*Math.max(1,Number(qty)||1))}</b></div><div className="buySell"><button onClick={()=>trade("buy")}>BUY</button><button onClick={()=>trade("sell")}>SELL</button></div><div className="cash">AVAILABLE CASH <b>₹{money(portfolio.cash)}</b></div><div className="directory"><h3>COMPANY DIRECTORY</h3>{COMPANIES.map(c=><button key={c.ticker} onClick={()=>setSelected(c.ticker)}><b>{c.ticker}</b><span>{c.name}</span></button>)}</div></aside></section><section className="bottom"><div className="news"><h3>MARKET NEWS</h3>{market.news.slice(0,5).map(n=><div key={n.id}><span>{n.tone==="up"?"▲":n.tone==="down"?"▼":"•"}</span>{n.text}</div>)}</div><div className="leader"><h3><Trophy size={16}/> LIVE LEADERBOARD</h3>{leaderboard.length?leaderboard.slice(0,8).map((p,i)=><div key={p.clientId||i}><b>#{i+1} {p.name}</b><span>₹{money(p.worth)}</span></div>):<div className="muted">Players appear here as they join.</div>}</div></section></>}
    {tab==="portfolio"&&<section className="portfolio"><div className="portHero"><div><span>YOUR PORTFOLIO</span><h2>₹{money(netWorth)}</h2></div><div><span>CASH</span><b>₹{money(portfolio.cash)}</b></div><div><span>OPEN POSITIONS</span><b>{Object.keys(portfolio.holdings||{}).length}</b></div></div><div className="holdings">{COMPANIES.filter(c=>(portfolio.holdings?.[c.ticker]||0)>0).map(c=><div className="holding" key={c.ticker}><b>{c.ticker}</b><span>{c.name}</span><strong>{portfolio.holdings[c.ticker]} shares</strong><em>₹{money2((portfolio.holdings[c.ticker]||0)*market.prices[c.ticker])}</em></div>)}{!Object.keys(portfolio.holdings||{}).length&&<div className="empty">No holdings yet. Go to Market and place your first order.</div>}</div></section>}
    {tab==="control"&&isHost&&<section className="control"><div className="controlHead"><div><span>HEADMASTER CONSOLE</span><h2>Control the room</h2></div><div className="controlButtons"><button onClick={togglePause}>{market.paused?<Play/>:<Pause/>}{market.paused?"RESUME":"PAUSE"}</button><button onClick={reset}><RotateCcw/> RESET MARKET</button></div></div><div className="controlGrid"><div className="eventPanel"><h3><Send/> PUBLISH MARKET EVENT</h3><label>SCOPE</label><select value={eventScope} onChange={e=>{setEventScope(e.target.value);setEventTarget(e.target.value==="sector"?"Insurance":COMPANIES[0].ticker)}}><option value="market">Whole Market</option><option value="sector">Sector</option><option value="company">Company</option></select>{eventScope!=="market"&&<><label>TARGET</label><select value={eventTarget} onChange={e=>setEventTarget(e.target.value)}>{(eventScope==="sector"?SECTORS:COMPANIES.map(c=>c.ticker)).map(x=><option key={x}>{x}</option>)}</select></>}<label>PRICE IMPACT %</label><input type="number" value={eventPct} onChange={e=>setEventPct(e.target.value)}/><label>HEADLINE</label><input value={headline} onChange={e=>setHeadline(e.target.value)} placeholder="e.g. Government announces a new contract"/><button className="publish" onClick={fireEvent}><Zap/> PUBLISH EVENT</button></div><div className="playersPanel"><h3><Users/> PLAYERS ({players.length})</h3>{leaderboard.map((p,i)=><div className="playerRow" key={p.clientId||i}><span><b>#{i+1}</b> {p.name}</span><strong>₹{money(p.worth)}</strong></div>)}{!players.length&&<div className="muted">Waiting for players to join…</div>}<div className="share"><b>ROOM CODE</b><strong>{room}</strong><button onClick={copyRoom}><Copy size={15}/> COPY</button></div></div></div></section>}
    </main><footer>STOCKEX • Educational simulation • Prices are simulated • No real money</footer></div>;
}
export default App;
